apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: pythonflask
        image: minhajkadri/pyflask
        ports:
        - containerPort: 5000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: python
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
