name: deploy to k8s
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build and push docker image"]
    types: [requested]
    branches:
      - 'githubaction'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: mkdir -p ${HOME}/.kube
     - run: echo "${{ secrets.BOUNCYKUBECONFIG }}" > ${HOME}/.kube/config
     - run: chmod 600 ${HOME}/.kube/config
     - run: kubectl config use-context c51p031-admin  # Replace with your desired Kubernetes context
     - run: kubectl get ns
     
