name: Deploy to Kubernetes

 

on:

  push:

    branches:

      - main

 

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

 

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

 

      - name: Build & Push Docker Image

        run: |

          echo "${{ secrets.DOCKERPW }}" | docker login -u "minhajkadri" --password-stdin

          docker image build -t minhajkadri/pyflask:latest .

          docker push minhajkadri/pyflask:latest

 

      - name: Create kubeconfig

        run: |

          mkdir -p ${HOME}/.kube

          echo "${{ secrets.BOUNCYKUBECONFIG }}" > ${HOME}/.kube/config

          chmod 600 ${HOME}/.kube/config

          kubectl config use-context mikadri  # Replace with your desired Kubernetes context

 

      - name: Deploy to Kubernetes

        run: |

          kubectl apply -f deploymentservice.yml -n mikadri
