---
name: Deploy to Kubernetes
on:
  push:
    branches:
      - main
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build & Push Docker Image
        run: >
          
          echo "${{ secrets.DOCKERPW }}" | docker login -u "minhajkadri" --password-stdin


          docker image build -t minhajkadri/pyflask:$(date +'%Y%m%d%H%M%S')} .


          docker push minhajkadri/pyflask:$(date +'%Y%m%d%H%M%S')

permissions:
  actions: ubuntu-latest
  checks: build_test
   issues:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Create kubeconfig
       run: >
        
        mkdir -p ${HOME}/.kube


        echo "${{ secrets.BOUNCYKUBECONFIG }}" > ${HOME}/.kube/config


        chmod 600 ${HOME}/.kube/config


        kubectl config use-context c51p031-admin  # Replace with your desired Kubernetes context
     - name: Deploy to Kubernetes
       run: |
        
        #kubectl apply -f deploymentservice.yml -n mikadri
         kubectl get ns
