name: Deploy to Kubernetes

 

on:

  push:

    branches:

      - main

 

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

 

    steps:

      - name: Checkout code

        uses: actions/checkout@v2
        
     
      # - name: Get current date
      #   id: date
      #   run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      # - name: Test with environment variables
      #   run: echo $TAG_NAME - $RELEASE_NAME
      #   env:
      #     TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
      #     RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
      # - name: Test with input
      #   uses: actions/hello-world-docker-action@master
      #   with:
      #     who-to-greet: Mona-the-Octocat-${{ steps.date.outputs.date }}

      
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Set date and time as a tag
        run: |
          TAG=$(date +'%Y%m%d%H%M%S')
          # echo "Image tag: $TAG" >> $GITHUB_ENV
 
 

      - name: Build & Push Docker Image

        run: |

          echo "${{ secrets.DOCKERPW }}" | docker login -u "minhajkadri" --password-stdin

          docker image build -t minhajkadri/pyflask:${TAG} .

          docker push minhajkadri/pyflask:${TAG}

 

      # - name: Create kubeconfig

      #   run: |

      #     mkdir -p ${HOME}/.kube

      #     echo "${{ secrets.BOUNCYKUBECONFIG }}" > ${HOME}/.kube/config

      #     chmod 600 ${HOME}/.kube/config

      #     kubectl config use-context c51p031-admin  # Replace with your desired Kubernetes context

 

      # - name: Deploy to Kubernetes

      #   run: |

      #     #kubectl apply -f deploymentservice.yml -n mikadri
      #     kubectl get ns
